# Generated by Django 4.1.2 on 2022-10-11 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conductor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('licencia', models.IntegerField()),
                ('foto_licencia', models.ImageField(upload_to='media')),
                ('foto_conductor', models.ImageField(upload_to='media')),
                ('antecedentes', models.CharField(max_length=50)),
            ],
        ),
    ]
