# Generated by Django 4.1.2 on 2022-10-11 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conductores', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conductor',
            options={'verbose_name': 'Conductor', 'verbose_name_plural': 'Conductores'},
        ),
    ]
