# Generated by Django 4.1.2 on 2022-10-11 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='nombre_vehiculo',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
