# Generated by Django 4.1.2 on 2022-10-11 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=70)),
                ('apellidos', models.CharField(max_length=50)),
                ('genero', models.CharField(choices=[('0', 'Masculino'), ('1', 'Femenino'), ('2', 'Otro')], default='0', max_length=2)),
                ('cedula', models.IntegerField()),
                ('foto_persona', models.ImageField(upload_to='media')),
                ('numero_telefono', models.IntegerField()),
                ('correo', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
            },
        ),
        migrations.CreateModel(
            name='TipoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_referido', models.CharField(max_length=50)),
            ],
        ),
    ]
