# Generated by Django 4.0.6 on 2022-09-28 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_persona', models.CharField(max_length=50, verbose_name='Nombre')),
                ('apellido_persona', models.CharField(max_length=50, verbose_name='Apellido')),
                ('genero', models.CharField(choices=[('1', 'Masculino'), ('2', 'Femenino'), ('3', 'Otro')], max_length=3, verbose_name='Genero')),
                ('cedula_persona', models.PositiveBigIntegerField()),
                ('celular_persona', models.IntegerField()),
                ('foto_persona', models.ImageField(upload_to='media', verbose_name='Foto')),
                ('correo', models.EmailField(max_length=50, verbose_name='Correo')),
                ('rol_persona', models.BooleanField(default=False)),
            ],
        ),
    ]
